### PR TITLE
Update for Thunderbird 102

### PR DESCRIPTION
**Pull request by jobisoft**
This is an update for Thunderbird 102. The current version loads, but has the tab names "Quota" and "Flags" in the wrong order. 

This PR also further removes dependencies on legacy code, by removing old DTD and property files and using the i18n files instead. The WindowListener API is loading them for you.

It should be backward compatible.

### CODE REVIEW

**Comment by voccs** [comment]
Thanks much.

Getting a validation error that doesn't appear to be correct when uploading the latest xpi:

> Your add-on failed validation with 1 error.
>
>    A "strict_max_version" is required for Thunderbird Mail Experiments.

The full validation report contains no traces of this error.

**Comment by jobisoft** [comment]
Yes, you must add a `strict_max_version` setting. You will get a warning that it is not needed, but Experiments need a strict_max_version.

**Comment by voccs** [comment]
https://github.com/voccs/folderflags/blob/af4eb955239315be69cebb41cd454608376c734a/manifest.json#L7 ?

**Comment by jobisoft** [comment]
Looks good!

**Comment by voccs** [comment]
That was already present in the XPI I uploaded, thus "error that doesn't appear to be correct."

**Comment by jobisoft** [comment]
I was able to test-upload this version and it passed validation without issue (6 warning but nothing that prevents the submission). 

Could you give it another try? I suspect there was something wrong or ATN had a bad day
[folderflags-master.zip](https://github.com/voccs/folderflags/files/9090535/folderflags-master.zip)

**Pull request merged**
